esp-rs/esp-pacs

xtask/src/main.rs

This contains basically two small things
- pass `build-std=core` and the right target to svd2rust
- a "quality of life" addition: a "--patch-only" option to omit all the steps after patching the SVD - that's because for me it usually takes some iterations to make a patch produce the desired output ... not really needed but can speed up things a bit
Maybe we should use CLAP for the parameters and also add a "--help" option. However, it's not really an end-user crate and I cannot think of much more options to add - so I'm not sure about that
But generally, this repo is a big step forward - I really like the absence of _make_ and _Python_ - not to mention the monorepo

Minor improvements

---

Cargo.lock
esp32/Cargo.toml
esp32s2/Cargo.toml
esp32s2/svd/patches/esp32s2.yaml
esp32s3/Cargo.toml
esp32s3/svd/patches/esp32s3.yaml

* ESP32S2 support
* prepare for ESP32S3
* use `xtensa-lx-rt` version _0.9.0_ 
Note: After this also `esp-hal` needs an update

Enable basic ESP32S2 support, prepare for ESP32S3 support

---

esp32c3/svd/patches/esp32c3.yaml

This aligns the naming of `INT_ENA_TIMERS` and `INT_ST_TIMERS` registers.
This is in preparation for (simple) timer interrupt support.

Align timer interrupt register names

---

esp32/svd/patches/esp32.yaml
esp32c3/svd/patches/esp32c3.yaml
esp32s2/svd/patches/esp32s2.yaml
esp32s3/svd/patches/esp32s3.yaml

This is a simple peripheral with only a single register.
`baseAddress` and `addressOffset` values were deduced by a combination of searching ESP-IDF with `ripgrep` for the term __WDEV_RND_REG__ and referring to the TRM.
@bjoernQ everything seems to be working as expected in my examples, but whenever you get a moment could you please confirm these values are correct?

Patch in the register for the hardware RNG for each chip

---

Cargo.lock
README.md
xtask/Cargo.toml
xtask/src/main.rs

Makes some minor improvements to the xtask:
- One or more chip can now be specified, where as only one was supported previously. Providing no chips runs the task for all chips.
- Added some simple logging, just to indicate where in the process we currently are.

Add support for multiple chip arguments, add logging

---

Cargo.lock
esp32/Cargo.toml
esp32s2/Cargo.toml
esp32s3/Cargo.toml
esp8266/Cargo.toml

This just updates the xtensa-lx-rt dependency to 0.10.0 in preparation of the next PR in esp-hal

Update xtensa-lx-rt version to 0.10.0

---

esp32s2/svd/patches/_systimer.yaml
esp32s2/svd/patches/esp32s2.yaml

Rename fields & registers of esp32s2  systimer to get them in line with the C3 & S3 systimer.
I also spent (way too long lol) trying to get the conf, hi & lo registers to act as arrays but I couldn't get it working.

rename fields & registers of esp32s2 

---

esp32/svd/patches/esp32.yaml
esp32c3/svd/patches/esp32c3.yaml
esp32s2/svd/patches/esp32s2.yaml
esp32s3/svd/patches/esp32s3.yaml

Problem was that on S2 and S3 there were names like `T1CONFIG/T0_xxxx` ... this strips the `Tn_` prefix from the field names.
Unfortunately, this PR will break the current HAL version so I will pin the dependencies there to a commit instead of just using the branch `with_sources`

Align TIMG field names

---

esp32/svd/patches/esp32.yaml

Changes `access` of `DUTY_xSCHx` fields in `xSHz_DUTY` registers.
Rename `DIV_NUM_LSTIMERx` into `CLK_DIV_LSTIMERx` fields in  `LSTIMERx_CONF` registers

[esp32] Change access and align LEDC related registers

---

esp32/svd/patches/esp32.yaml
esp32c3/svd/patches/esp32c3.yaml
esp32s2/svd/patches/esp32s2.yaml
esp32s3/svd/patches/esp32s3.yaml

This should make the naming of registers and fields for the `LEDC` peripheral as similar as possible. The ESP32 will always differ from the rest due to its low/high speed channels, but the register structure otherwise matches the other chips.
This does rename a number of registers and fields obviously, so updates will be required in the PR for the HAL. However, once those changes are made then we should be able to support the S2 and S3 fairly trivially. I have not modified any interrupt-related registers, as interrupt support for this peripheral is not implemented in the PR.
@bjoernQ @JurajSadel PTAL and let me know if you spot any issues. Probably easiest to run each SVD through [svd2html](https://github.com/bjoernQ/svd2html) for visual comparison (which is what I've done, comparing with …

Align LEDC register and field names across chips

---

esp32c3/svd/patches/esp32c3.yaml

This pull request adds read-write access to the TWAI_DATA_x_REG registers. These registers need read access in order to access the TWAI receive buffer and write access in order to access the transmit buffer. 
I created an issue in the parent SVD repo:
https://github.com/espressif/svd/issues/24
While testing a Rust TWAI driver locally, reading from these registers did seem to work properly for receiving packets.
Not sure if this should also be applied to other svds as I only have an ESP32C3.

Add read-write access to TWAI DATA_x registers.

---

esp32s3/Cargo.toml
esp32s3/src/apb_saradc.rs
esp32s3/src/apb_saradc/arb_ctrl.rs
esp32s3/src/apb_saradc/clkm_conf.rs
esp32s3/src/sens/sar_amp_ctrl3.rs
esp32s3/src/sens/sar_atten1.rs
esp32s3/src/sens/sar_atten2.rs
esp32s3/src/sens/sar_hall_ctrl.rs
esp32s3/src/sens/sar_meas1_ctrl1.rs
esp32s3/src/sens/sar_meas1_ctrl2.rs
esp32s3/src/sens/sar_meas1_mux.rs
esp32s3/src/sens/sar_meas2_ctrl2.rs
esp32s3/src/sens/sar_meas2_mux.rs
esp32s3/src/sens/sar_peri_clk_gate_conf.rs
esp32s3/src/sens/sar_power_xpd_sar.rs
esp32s3/svd/patches/esp32s3.yaml

Needed for [ADC](https://github.com/esp-rs/esp-hal/tree/main/esp-hal-common/src/analog/adc) refactor in [esp-hal](https://github.com/esp-rs/esp-hal).

S3: Remove SAR prefix in SENS peripheral

---

esp32s2/svd/patches/esp32s2.yaml

Note that stripping `OP` now gives `continue_` which is the same as others, but we might want to patch all of the others to have the register be `continue`

Patch SHA registers for S2 chip to be consistent with others (C2/C3/S3)

---

esp32s3/svd/patches/esp32s3.yaml

This is needed for the upcoming I2S implementation
This only includes the changed patch-file - not the updated sources.
Not sure what the policy should be - probably including updated sources in PRs would be annoying
Maybe we should have some hints in the README PRs should look like?

Strip prefixes from ESP32-S3 I2S1

---

esp32/Cargo.toml
esp32s2/Cargo.toml
esp32s3/Cargo.toml

In order to prepare a small change in esp-hal ( https://github.com/esp-rs/xtensa-lx-rt/pull/50 ) we first need to update all its dependencies
I didn't update ESP-8266 - I guess no-one will update that HAL
Unfortunately, we'll also need to bump the versions of ESP32, ESP32-S2 and ESP32-S3 and release them :(

Update xtensa-lx-rt to 0.14.0

---

esp32s2/src/pcnt/u_cnt.rs
esp32s2/src/pcnt/u_conf0.rs
esp32s2/src/pcnt/u_conf1.rs
esp32s2/src/pcnt/u_conf2.rs
esp32s2/svd/patches/esp32s2.yaml

rename some PCNT register fields to remove the unit number
where the register is unit specific.

rename esp32s2 PCNT register fields to be consistent with esp32s3

---

esp32/src/pcnt/u_status.rs
esp32/svd/patches/esp32.yaml
esp32s2/src/pcnt/u_status.rs
esp32s2/svd/patches/esp32s2.yaml
esp32s3/src/pcnt/u_status.rs
esp32s3/svd/patches/esp32s3.yaml

made status register field names consistent across esp32/esp32s2/esp32s3

PCNT status register field names for esp32/esp32s2/esp32s3

---

esp32c2/Cargo.toml
esp32c3/Cargo.toml
esp32c6/Cargo.toml
esp32h2/Cargo.toml

New releases of `riscv` and `riscv-rt` are now available.

Bump dependencies for RISC-V chips

---

README.md
xtask/Cargo.lock
xtask/Cargo.toml
xtask/src/main.rs

This is mostly to pull in the latest `svdtools`, which (finally) supports patching of `<dim*>` elements. Also just updates and cleans up the `xtask` a bit, though.

Update `xtask` and its dependencies

---

esp32/Cargo.toml
esp32c2/Cargo.toml
esp32c3/Cargo.toml
esp32c6/Cargo.toml
esp32h2/Cargo.toml
esp32s2/Cargo.toml
esp32s3/Cargo.toml

First change for what was discussed in https://github.com/esp-rs/esp-hal/issues/382
For Xtensa it still needs `xtensa-lx` but that is less of a problem since it changes not that frequently. Would be better to not need it but that's how svd2rust generates the code currently. (I don't think we need that in our HALs but not a big deal IMHO)

Remove dependency to rt-crates

---

.github/actions/check/action.yml
.github/workflows/ci.yml

We had maxed out on our concurrency with the addition of the PACs for the coprocessors, and given that we have more chips coming in the future I figured it was time to address this.
I've created an action which will check a package using both the latest version as well as the MSRV, using the correct toolchain and all that. This action is now invoked for each package, giving us plenty of room to expand for the foreseeable future.

Rewrite the CI workflow

---

esp32h2/src/ecc.rs
esp32h2/src/ecc/qx_mem.rs
esp32h2/src/ecc/qy_mem.rs
esp32h2/src/ecc/qz_mem.rs
esp32h2/svd/patches/esp32h2.yaml

Leaving this as a draft for now, maybe I missed something else, will verify and update it tomorrow.

ESP32H2: Add Qx, Qy and Qz memory block to ECC peripheral

---

esp32/src/rsa/modexp_mode.rs
esp32/src/rsa/mult_mode.rs
esp32/svd/patches/esp32.yaml

After checking with the `TRM` for the ESP32 chip, I found out that the bit widths of these two registers do not match the documentation.

Fix `MULT_MODE` and `MODEXP_MODE` fields for `ESP32`

---

.github/workflows/ci.yml
README.md
esp32/Cargo.toml
esp32c2/Cargo.toml
esp32c3/Cargo.toml
esp32c6-lp/Cargo.toml
esp32c6/Cargo.toml
esp32h2/Cargo.toml
esp32s2-ulp/Cargo.toml
esp32s2/Cargo.toml
esp32s3-ulp/Cargo.toml
esp32s3/Cargo.toml
esp8266/Cargo.toml
xtask/Cargo.lock
xtask/Cargo.toml

While there's no particular need to bump the MSRV, we may as well just keep them in-line with `esp-hal`'s MSRV. Not much point in having them lower, IMO.
Also updated `xtask` to get the latest versions of `svd2rust` and `svdtools`.

Bump MSRV to 1.67.0 and update `xtask`

---

esp32/src/uart0/mem_cnt_status.rs
esp32/src/uart0/mem_conf.rs
esp32/svd/patches/esp32.yaml
esp32c6-lp/src/lp_io/gpio.rs
esp32c6-lp/svd/patches/esp32c6-lp.yaml

Correct name of `LP_IO::GPIO%s` field for ESP32-C6 LP, fix typos in ESP32 UART descriptions

---

esp32s3/src/lcd_cam/cam_ctrl.rs
esp32s3/src/lcd_cam/cam_ctrl1.rs
esp32s3/src/lcd_cam/lcd_clock.rs
esp32s3/src/lcd_cam/lcd_user.rs
esp32s3/svd/patches/esp32s3.yaml

Just covered a few registers in this PR, but I'm not going to go through and verify every single one right now 😁 It's a good start, at least.
Closes #179

Correct/improve some field descriptions for ESP32-S3's `LCD_CAM` peripheral

---

esp32/src/lib.rs
esp32c2/src/lib.rs
esp32c3/src/lib.rs
esp32c6-lp/src/lib.rs
esp32c6/src/lib.rs
esp32h2/src/lib.rs
esp32p4/src/lib.rs
esp32s2-ulp/src/lib.rs
esp32s2/src/lib.rs
esp32s3-ulp/src/lib.rs
esp32s3/src/lib.rs
xtask/src/main.rs

This is a first step to make https://github.com/esp-rs/esp-hal/issues/1063 happen
And probably it's a good idea to move the interrupt vectors to RAM in general. We had it before for Xtensa but for RISC-V it was on flash

Use rwtext as link section

---

esp32h2/src/lib.rs
esp32h2/svd/patches/esp32h2.yaml

The base-address for 802.15.4 was wrong for ESP32-H2 - fixed via patch

ESP32-H2: Fix 802.15.4 base-address

---

common_patches/i2c0.yaml
common_patches/i2c_opcode.yaml
esp32/svd/patches/esp32.yaml
esp32c2/src/i2c0/comd.rs
esp32c3/src/i2c0/comd.rs
esp32c6/src/i2c0/comd.rs
esp32h2/src/i2c0/comd.rs
esp32p4/src/i2c0/comd.rs
esp32s2/svd/patches/esp32s2.yaml
esp32s3/src/i2c0/comd.rs

Related to https://github.com/esp-rs/esp-hal/issues/1916
Data are taken from `i2c_ll.h` files for each chip in `esp-idf` (e.g. https://github.com/espressif/esp-idf/blob/master/components/hal/esp32c6/include/hal/i2c_ll.h#L45-L49)

Fix `I2C/COMD/OPCODE` values

---

esp32/Cargo.toml
esp32s3/Cargo.toml

Nothing seems to use it and the spinlocking mutex implementation doesn't exactly belong in xtensa-lx so I'm planning to remove it from there.

Don't enable xtensa-lx/spin

---

common_patches/i2c0.yaml
esp32/src/i2c0/int_clr.rs
esp32/src/i2c0/int_ena.rs
esp32/src/i2c0/int_raw.rs
esp32/src/i2c0/int_st.rs
esp32/svd/patches/esp32.yaml

Allows cleaning up things like https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/i2c.rs#L650-L653

ESP32 I2C: Rename ACK_ERR to NACK

---

esp32c6/src/clint.rs
esp32c6/src/clint/msip.rs
esp32c6/src/clint/mtime.rs
esp32c6/src/clint/mtimecmp.rs
esp32c6/src/clint/mtimectl.rs
esp32c6/src/clint/usip.rs
esp32c6/src/clint/utime.rs
esp32c6/src/clint/utimecmp.rs
esp32c6/src/clint/utimectl.rs
esp32c6/src/lib.rs
esp32c6/svd/patches/esp32c6.yaml
esp32h2/src/clint.rs
esp32h2/src/clint/msip.rs
esp32h2/src/clint/mtime.rs
esp32h2/src/clint/mtimecmp.rs
esp32h2/src/clint/mtimectl.rs
esp32h2/src/clint/usip.rs
esp32h2/src/clint/utime.rs
esp32h2/src/clint/utimecmp.rs
esp32h2/src/clint/utimectl.rs
esp32h2/src/lib.rs
esp32h2/svd/patches/esp32h2.yaml

Copied from the TRM, should hopefully be correct but would appreciate some additional review here.

Add the CLINT peripheral for ESP32-C6 and ESP32-H2

---

Cargo.lock
esp32/Cargo.toml
esp32s2/Cargo.toml
esp32s3/Cargo.toml
xtask/src/main.rs

Draft until https://github.com/rust-embedded/svd2rust/pull/883 is merged and preferably released.

Remove dependency on xtensa-lx

---

common_patches/usb0.yaml
esp32s2/src/usb0/hc/char.rs
esp32s3/src/usb0/hc/char.rs

Have not tested on hardware but in theory it should be correct.
Closes #305

Correct bit width and offset for USB0:HCCHAR:EC field

---

esp32s2/src/copy_dma.rs
esp32s2/src/copy_dma/conf.rs
esp32s2/svd/patches/esp32s2.yaml

Make `COPY_DMA.CONF` register read-write

---

esp32h2/src/lib.rs
esp32h2/src/lp_apm0.rs
esp32h2/src/lp_apm0/clock_gate.rs
esp32h2/src/lp_apm0/date.rs
esp32h2/src/lp_apm0/func_ctrl.rs
esp32h2/src/lp_apm0/int_en.rs
esp32h2/src/lp_apm0/m0_exception_info0.rs
esp32h2/src/lp_apm0/m0_exception_info1.rs
esp32h2/src/lp_apm0/m0_status.rs
esp32h2/src/lp_apm0/m0_status_clr.rs
esp32h2/src/lp_apm0/region0_addr_end.rs
esp32h2/src/lp_apm0/region0_addr_start.rs
esp32h2/src/lp_apm0/region0_pms_attr.rs
esp32h2/src/lp_apm0/region1_addr_end.rs
esp32h2/src/lp_apm0/region1_addr_start.rs
esp32h2/src/lp_apm0/region1_pms_attr.rs
esp32h2/src/lp_apm0/region2_addr_end.rs
esp32h2/src/lp_apm0/region2_addr_start.rs
esp32h2/src/lp_apm0/region2_pms_attr.rs
esp32h2/src/lp_apm0/region3_addr_end.rs
esp32h2/src/lp_apm0/region3_addr_start.rs
esp32h2/src/lp_apm0/region3_pms_attr.rs
esp32h2/src/lp_apm0/region_filter_en.rs
esp32h2/svd/patches/esp32h2.yaml

This adds the LP_APM0 peripheral for ESP32-H2. It's just a copy of the same peripheral on ESP32-C6

Add LP_APM0 for ESP32-H2

---

common_patches/i2c_st_timeouts.yaml
esp32c2/src/i2c0/scl_main_st_time_out.rs
esp32c2/src/i2c0/scl_st_time_out.rs
esp32c2/svd/patches/esp32c2.yaml
esp32c3/src/i2c0/scl_main_st_time_out.rs
esp32c3/src/i2c0/scl_st_time_out.rs
esp32c3/svd/patches/esp32c3.yaml
esp32c6/src/i2c0/scl_main_st_time_out.rs
esp32c6/src/i2c0/scl_st_time_out.rs
esp32c6/svd/patches/esp32c6.yaml
esp32h2/src/i2c0/scl_main_st_time_out.rs
esp32h2/src/i2c0/scl_st_time_out.rs
esp32h2/svd/patches/esp32h2.yaml
esp32p4/src/i2c0/scl_main_st_time_out.rs
esp32p4/src/i2c0/scl_st_time_out.rs
esp32p4/svd/patches/esp32p4.yaml
esp32s3/src/i2c0/scl_main_st_time_out.rs
esp32s3/src/i2c0/scl_st_time_out.rs
esp32s3/svd/patches/esp32s3.yaml

Remove the `_I2C` postfix from I2C-ST timeout fields

Remove the `_I2C` postfix from I2C-ST timeout fields

---

esp32c6/src/slc.rs
esp32c6/src/slc/slc0_length.rs
esp32c6/svd/patches/esp32c6.yaml

Fixes a typo in the SLC0_LENGTH register name in the SVD YAML patch file.
Re-generates the `esp32c6` PAC with the SLC0_LENGTH register name fix.

esp32c6: fix SLC0_LENGTH register name 

---

esp32c3/src/lib.rs
esp32c3/svd/patches/esp32c3.yaml

This chip does not have a UHCI1 peripheral - at least not according to the TRM or esp-idf source code.

C3: remove UHCI1

---

esp32s3/device.x
esp32s3/src/lib.rs
esp32s3/svd/patches/esp32s3.yaml

Same deal as with https://github.com/esp-rs/esp-pacs/pull/374
Only ESP32 and S2 seem to have 2 UHCI peripherals.

S3: Remove UHCI1
