esp-rs/esp-pacs

esp32/svd/patches/esp32.yaml
esp32c3/svd/patches/esp32c3.yaml
esp32s2/svd/patches/esp32s2.yaml

These changes prepare the upcoming _I2C_ PR in _esp-hal_

Patches to align I2C peripherals

---

Cargo.lock
esp32/Cargo.toml
esp32s2/Cargo.toml
esp32s3/Cargo.toml
esp8266/Cargo.toml

This updates xtensa-lx-rt dependency to the most recent version

Update xtensa-lx-rt version to 0.11.0

---

esp32c3/device.x
esp32c3/svd/patches/esp32c3.yaml

[esp32c3] Add the `SW_INTR_*` interrupts to the `INTERRUPT_CORE0` peripheral

---

esp32/device.x
esp32/svd/patches/esp32.yaml
esp32c3/device.x
esp32c3/svd/patches/esp32c3.yaml
esp32s2/device.x
esp32s2/svd/patches/esp32s2.yaml
esp32s3/device.x
esp32s3/svd/patches/esp32s3.yaml

Closes #25 
If you think there are better peripherals to attach these to, please let me know!

Add WiFi and bluetooth interrupts for each chip

---

esp32s2/svd/patches/esp32s2.yaml
esp32s3/svd/patches/esp32s3.yaml

This aligns some RTC related registers to prepare for DAC implementation (ESP32, ESP32S2)
Also contains some changes in preparation for general analog functionality on ESP32S3

Align some RTC related registers

---

README.md
esp32s3/Cargo.toml
esp32s3/src/pwm0/timer1_sync.rs
esp32s3/src/pwm0/timer2_sync.rs
esp32s3/svd/patches/esp32s3.yaml

Okay, I think this should be correct this time 😁 @dimpolo are you able to confirm nothing else needs patching at this time for this peripheral please?
(Hopefully) closes #57

Additional corrections for ESP32-S3's MCPWM peripheral

---

esp32s2/device.x
esp32s2/src/lib.rs
esp32s2/svd/patches/esp32s2.yaml
esp32s3/device.x
esp32s3/src/lib.rs
esp32s3/svd/patches/esp32s3.yaml

Add the `USB` interrupt for the ESP32-S2/S3

---

esp32c6/src/dma/in_int_ena_ch.rs
esp32c6/src/dma/in_int_st_ch.rs
esp32c6/src/dma/out_int_ena_ch.rs
esp32c6/src/dma/out_int_st_ch.rs
esp32c6/src/twai0.rs
esp32c6/src/twai0/bus_timing_1.rs
esp32c6/src/twai0/cmd.rs
esp32c6/src/twai0/data_0.rs
esp32c6/src/twai0/data_1.rs
esp32c6/src/twai0/data_10.rs
esp32c6/src/twai0/data_11.rs
esp32c6/src/twai0/data_12.rs
esp32c6/src/twai0/data_2.rs
esp32c6/src/twai0/data_3.rs
esp32c6/src/twai0/data_4.rs
esp32c6/src/twai0/data_5.rs
esp32c6/src/twai0/data_6.rs
esp32c6/src/twai0/data_7.rs
esp32c6/src/twai0/data_8.rs
esp32c6/src/twai0/mode.rs
esp32c6/src/twai0/rx_message_cnt.rs
esp32c6/src/twai0/status.rs
esp32c6/svd/patches/esp32c6.yaml

This gets everything building in the HAL for these peripherals.

ESP32-C6 patches for `DMA` and `TWAI`

---

esp32/Cargo.toml
esp32s2/Cargo.toml
esp32s3/Cargo.toml

Bump xtensa-lx for ESP32/ESP32-S2/ESP32-S3

---

esp32/src/lib.rs
esp32/src/rsa.rs
esp32/src/rsa/m_mem.rs
esp32/src/rsa/x_mem.rs
esp32/src/rsa/y_mem.rs
esp32/src/rsa/z_mem.rs
esp32/svd/patches/esp32.yaml
esp32c3/src/lib.rs
esp32c3/src/rsa.rs
esp32c3/svd/patches/esp32c3.yaml
esp32c6/src/rsa.rs
esp32c6/svd/patches/esp32c6.yaml
esp32h2/src/rsa.rs
esp32h2/svd/patches/esp32h2.yaml
esp32s2/src/lib.rs
esp32s2/src/rsa.rs
esp32s2/src/rsa/m_mem.rs
esp32s2/src/rsa/x_mem.rs
esp32s2/src/rsa/y_mem.rs
esp32s2/src/rsa/z_mem.rs
esp32s2/svd/patches/esp32s2.yaml
esp32s3/src/lib.rs
esp32s3/src/rsa.rs
esp32s3/svd/patches/esp32s3.yaml

I believe these changes are correct as I have checked them against the TRMs, but just to be safe @matrixhead would you mind taking a quick look at this when you get a chance please?
This can also be done at least for the `DS` peripheral, possibly others, so I'll take care of that in a later PR.

Fix the memory blocks of the `RSA` peripheral

---

esp32c2/src/ecc.rs
esp32c2/src/ecc/k_mem.rs
esp32c2/src/ecc/px_mem.rs
esp32c2/src/ecc/py_mem.rs
esp32c2/svd/patches/esp32c2.yaml

[esp32c2] Add missing memory regions for `ECC` peripheral

---

esp32h2/src/pcnt/ctrl.rs
esp32h2/src/pcnt/int_clr.rs
esp32h2/src/pcnt/int_ena.rs
esp32h2/src/pcnt/int_raw.rs
esp32h2/src/pcnt/int_st.rs
esp32h2/src/pcnt/u_cnt.rs
esp32h2/src/pcnt/u_conf0.rs
esp32h2/src/pcnt/u_conf1.rs
esp32h2/src/pcnt/u_conf2.rs
esp32h2/src/pcnt/u_status.rs
esp32h2/svd/patches/esp32h2.yaml

Not sure if the modifications could be done better, but they seem to work

esp32h2: Align PCNT names with other devices

---

esp32c3/src/efuse.rs
esp32c3/src/efuse/clk.rs
esp32c3/src/efuse/conf.rs
esp32c3/src/efuse/wr_tim_conf1.rs
esp32c3/src/efuse/wr_tim_conf2.rs
esp32c3/src/system.rs
esp32c3/src/system/edma_ctrl.rs
esp32c3/svd/patches/esp32c3.yaml

I fixed typo that I found in efuse.rs

fix typo in efuse.rs

---

esp32c2/Cargo.toml
esp32c3/Cargo.toml
esp32c6/Cargo.toml
esp32h2/Cargo.toml

New PACs for ESP32-C2/C3/C6/H2

New package releases

---

esp32/src/timg0.rs
esp32/src/timg0/t0update.rs
esp32/src/timg0/t1update.rs
esp32/svd/patches/esp32.yaml
esp32c2/src/timg0/t0update.rs
esp32c2/svd/patches/esp32c2.yaml

This is needed for https://github.com/esp-rs/esp-hal/pull/1183

Patch TIMG/UPDATE for ESP32, ESP32-C2

---

esp32c6/src/gpio.rs
esp32c6/svd/patches/esp32c6.yaml

Fixes https://github.com/esp-rs/esp-hal/actions/runs/8494136810/job/23268914510#step:5:154

Add GPIO 31 to C6 pac

---

esp32p4/src/lcd_cam/lcd_dly_mode_cfg1.rs
esp32p4/src/lcd_cam/lcd_dly_mode_cfg2.rs
esp32p4/svd/patches/esp32p4.yaml
esp32s3/src/lcd_cam/lcd_data_dout_mode.rs
esp32s3/svd/patches/esp32s3.yaml

Non-breaking change
Maybe need labels for breaking/non-breaking changes and chip series?

LCD_CAM collect DOUT_MODE

---

esp32/src/spi0.rs
esp32/src/spi0/date.rs
esp32/src/spi0/pin.rs
esp32/src/spi0/user1.rs
esp32/svd/patches/esp32.yaml
esp32s2/src/spi0.rs
esp32s2/src/spi0/cache_sctrl.rs
esp32s2/src/spi0/misc.rs
esp32s2/src/spi0/sram_clk.rs
esp32s2/src/spi0/sram_drd_cmd.rs
esp32s2/src/spi0/sram_dwr_cmd.rs
esp32s2/svd/patches/esp32s2.yaml
esp32s3/src/spi0/misc.rs
esp32s3/src/spi1/misc.rs
esp32s3/svd/patches/esp32s3.yaml

Is one of essential supplements for https://github.com/esp-rs/esp-hal/issues/1194 and https://github.com/esp-rs/esp-hal/pull/1854 specifically.

Add/edit PSRAM-related SPI registers

---

esp32c6/src/plic_mx.rs
esp32c6/src/plic_ux.rs
esp32c6/src/plic_ux/uxint_pri.rs
esp32c6/svd/patches/esp32c6.yaml
esp32h2/src/plic_mx.rs
esp32h2/src/plic_ux.rs
esp32h2/src/plic_ux/uxint_pri.rs
esp32h2/svd/patches/esp32h2.yaml

There was wrong offset step for those fields.

Fix dimIncrement for PLIC X_INT fields

---

esp32/src/twai0/clock_divider.rs
esp32/src/twai0/int_ena.rs
esp32/svd/patches/esp32.yaml

Fix TWAI, add missing field

---

esp32c6/src/rmt/sys_conf.rs
esp32c6/svd/patches/esp32c6.yaml
esp32h2/src/rmt/sys_conf.rs
esp32h2/svd/patches/esp32h2.yaml

Define reserved bits in `RMT_SYS_CONF_REG` for C6/H2

---

esp32c6/src/twai0/cmd.rs
esp32c6/svd/patches/esp32c6.yaml
esp32h2/src/twai0/cmd.rs
esp32h2/svd/patches/esp32h2.yaml

Align TWAI command register field names for C6/H2 with other chips

---

esp32/src/dport/peri_clk_en.rs
esp32/src/dport/peri_rst_en.rs
esp32/svd/patches/esp32.yaml

Add missing clk_en bits, fix typo
